### ISSUE TITLE
"failed to resolve reference "docker.io/library/controller:latest"

### ISSUE THREAD

**Issue by magic-jims** [pfnet/image-pull-secrets-provisioner#31]
Currently receiving the following error on the manager pod after running kubectl apply -k . in the config/default directory.

`Failed to pull image "controller:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/controller:latest": failed to resolve reference "docker.io/library/controller:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed`

Edit:

container is stuck in "ImagePullBackOff" status 
`image-pull-secrets-provisioner-system   controller-manager-7fd5f56d64-9c44h                         1/2     ImagePullBackOff  `

**Comment by ordovicia** [comment]
Hi @magic-jims 

`kustomize build ./config/default` (or `kubectl apply -k ./config/default`) will produce a Deployment resource definition that refers `controller:latest` image, which does not exist.
It is required to patch the resource to use an actual image.
You can use the following example `kustomization.yaml` to change the image name.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/pfnet/image-pull-secrets-provisioner//config/default?ref=v0.0.2
images:
- name: controller
  newName: ghcr.io/pfnet/image-pull-secrets-provisioner
  newTag: v0.0.2
```
